spring:
  application:
    name: dynamo
  jackson:
    default-property-inclusion: non_null
    serialization:

    deserialization:
      fail-on-unknown-properties: false


management:
  endpoint:
    shutdown:
      access: unrestricted
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


server:
  port: 8080
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

logging:
  level:
    root: INFO
    revenera.gcs: TRACE
    org.springframework.web: INFO

app:
  housekeeping:
    cron: "0 */1 * * * *"